addpackage: Improve error checking, file handling, and more
In particular:
	- Add the usage() function, invoking it on unknown options in
	the `getopts` loop and if "$SMLSS_DIR" does not exist.
	- Instead of appending to "$file" and then sorting "$file",
	concatenate "$file" and the list of packages, sort it, and then
	write to "$file".
	- Invoke `tr` and `sed` on "$pkgs" when needed throughout the
	code instead of assigning the result of those invocations to
	"$pkgs" every time. This improves speed because these
	transformations are only needed once.
	- Instead of `cd`-ing to $SMLSS_DIR, use `git -C "$SMLSS_DIR"`.
	"$file" is now an absolute path because of this.

diff --git a/addpackage b/addpackage
--- a/addpackage
+++ b/addpackage
@@ -7,32 +7,45 @@
 # Options:     -a        Add packages to the AUR list, not the Arch list.
 # Arguments:   names of packages to add
 
-options="ah"
+usage()
+{
+	echo "Usage: addpackage [-$options] packages..."
+}
+
+options="a"
 while getopts "$options" o; do
 	case "$o" in
-		a) aur="True" ;;
-		*) echo "USAGE: addpackage [-$options] packages..." && exit ;;
+		a) aur=1 ;;
+		*) usage && exit ;;
 	esac
 done
 
 shift $((OPTIND - 1))
-packages="$(echo "$*" | tr ' ' '\n')"
-file='packages.txt'
-[ "$aur" ] && file="aur-$file"
-cd "$SMLSS_DIR" # temporarily relocate to add to install lists and to make the commit
 
-echo -e "$packages" >> $file &&
-	sort $file | sponge $file &&
-	git add $file
+if [ "$#" -eq 0 ]; then
+	usage
+	exit
+fi
 
-# Change newlines to commas to make the list presentable for a git commit
-packages="$(echo "$packages" | sed 's/\\n/, /g')"
+pkgs="$*"
 
-commitmsg="$file: Add $packages"
-# Remove trailing comma from package list
-commitmsg="$(echo "$commitmsg" | sed 's/,$//')"
+if [ ! "$SMLSS_DIR" ]; then
+	# Single quotes intended, I don't want the value of $SMLSS_DIR here.
+	# shellcheck disable=SC2016
+	echo 'addpackage: error: $SMLSS_DIR does not exist.' >&2
+	exit 1
+fi
 
-git commit -vem "$commitmsg"
+if [ "$aur" ]; then
+	file="$SMLSS_DIR/aur-packages.txt"
+else
+	file="$SMLSS_DIR/packages.txt"
+fi
 
-cd - # teleport home
+echo "$pkgs" | tr ' ' '\n' | cat "$file" - | sort | sponge "$file" \
+	&& git -C "$SMLSS_DIR" add "$file"
+
+msg="$(basename "$file"): Add $(echo "$pkgs" | sed -e 's/ /, /g' -e 's/, $//')"
+
+git -C "$SMLSS_DIR" commit -vem "$msg"
 
