Restyle scripts to use `new` style of help/option parsing

diff --git a/src/cleanvideo b/src/cleanvideo
--- a/src/cleanvideo
+++ b/src/cleanvideo
@@ -8,6 +8,40 @@
 # cleanvideo
 #	Filters some background noise from a video.
 #	Optionally converts the format.
+# Arguments:
+#	input file, output file
 
-[ "$#" -eq 2 ] && ffmpeg -i "$1" -af "highpass=f=200, lowpass=f=3000" "$2"\
-	|| echo "Usage: clean-video in.format out.format"
+# Prints help information from the script's comment header.
+print_help()
+{
+	< "$0" awk '
+		/^#$/ {
+			getline  # skip the /^#$/ line
+			# loop until empty line
+			while (length) {
+				sub(/^# ?/, "")
+				print
+				getline
+			}
+			exit
+		}
+	'
+}
+
+options='h'
+while getopts "$options" o; do
+	case "$o" in
+		h) print_help; exit ;;
+		*) print_help >&2; exit 1 ;;
+	esac
+done
+
+shift $((OPTIND - 1))
+
+if [ "$#" -ne 2 ]; then
+	echo "$0: invalid arguments provided" >&2
+	print_help >&2
+	exit 1
+fi
+
+ffmpeg -i "$1" -af "highpass=f=200, lowpass=f=3000" "$2"
diff --git a/src/dh b/src/dh
--- a/src/dh
+++ b/src/dh
@@ -11,4 +11,41 @@
 #	The directory to read from.
 #	If one is not provided, the current directory is used.
 
+# Prints help information from the script's comment header.
+print_help()
+{
+	< "$0" awk '
+		/^#$/ {
+			getline  # skip the /^#$/ line
+			# loop until empty line
+			while (length) {
+				sub(/^# ?/, "")
+				print
+				getline
+			}
+			exit
+		}
+	'
+}
+
+options='h'
+while getopts "$options" o; do
+	case "$o" in
+		h) print_help; exit ;;
+		*) print_help >&2; exit 1 ;;
+	esac
+done
+
+shift $((OPTIND - 1))
+
+if [ "$#" -eq 1 ]; then
+	directory="$1"
+elif [ "$#" -eq 0 ]; then
+	directory='.'
+else
+	echo "$0: invalid arguments provided" >&2
+	print_help >&2
+	exit 1
+fi
+
 du -hd 1 "${1-.}" | sort -h
diff --git a/src/hd b/src/hd
--- a/src/hd
+++ b/src/hd
@@ -7,6 +7,41 @@
 #
 # hd
 #	Fuzzy find completion for haredoc.
+# Arguments:
+#	None. fzf reads input from the terminal.
+
+# Prints help information from the script's comment header.
+print_help()
+{
+	< "$0" awk '
+		/^#$/ {
+			getline  # skip the /^#$/ line
+			# loop until empty line
+			while (length) {
+				sub(/^# ?/, "")
+				print
+				getline
+			}
+			exit
+		}
+	'
+}
+
+options='h'
+while getopts "$options" o; do
+	case "$o" in
+		h) print_help; exit ;;
+		*) print_help >&2; exit 1 ;;
+	esac
+done
+
+shift $((OPTIND - 1))
+
+if [ "$#" -ne 0 ]; then
+	echo "$0: invalid arguments provided" >&2
+	print_help >&2
+	exit 1
+fi
 
 split_harepath()
 {
diff --git a/src/intlkey b/src/intlkey
--- a/src/intlkey
+++ b/src/intlkey
@@ -10,17 +10,39 @@
 # Options:
 #	-i	Instead of toggling the layout, print the active layout.
 
-usage()
+# Prints help information from the script's comment header.
+print_help()
 {
-	echo "usage: intlkey [-i]"
+	< "$0" awk '
+		/^#$/ {
+			getline  # skip the /^#$/ line
+			# loop until empty line
+			while (length) {
+				sub(/^# ?/, "")
+				print
+				getline
+			}
+			exit
+		}
+	'
 }
 
-while getopts "i" o; do
+options='hi'
+while getopts "$options" o; do
 	case "$o" in
+		h) print_help; exit ;;
 		i) i=1 ;;
-		*) usage; exit ;;
+		*) print_help >&2; exit 1 ;;
 	esac
 done
+
+shift $((OPTIND - 1))
+
+if [ "$#" -ne 0 ]; then
+	echo "$0: invalid arguments provided" >&2
+	print_help >&2
+	exit 1
+fi
 
 variant="$(setxkbmap -query | awk '/^variant:/ { print $2 }')"
 
